# secret shares the inputs for the three MPC nodes
split-input:
	co-noir split-input --input Alice.toml --circuit target/poseidon.json --protocol REP3 --out-dir out/secret_shared_inputs/
	RUST_LOG="error" co-noir split-input --input Bob.toml --circuit target/poseidon.json --protocol REP3 --out-dir out/secret_shared_inputs/

# For each MPC node, merges the secret shared inputs of Alice and Bob
merge-input:
	co-noir merge-input-shares --inputs out/secret_shared_inputs/Alice.toml.0.shared --inputs out/secret_shared_inputs/Bob.toml.0.shared --protocol REP3 --out out/merged_inputs/input.toml.0.shared 
	RUST_LOG="error" co-noir merge-input-shares --inputs out/secret_shared_inputs/Alice.toml.1.shared --inputs out/secret_shared_inputs/Bob.toml.1.shared --protocol REP3 --out out/merged_inputs/input.toml.1.shared 
	RUST_LOG="error" co-noir merge-input-shares --inputs out/secret_shared_inputs/Alice.toml.2.shared --inputs out/secret_shared_inputs/Bob.toml.2.shared --protocol REP3 --out out/merged_inputs/input.toml.2.shared 


# runs the extended witness generation on three nodes
run-witness-generation:
	co-noir generate-witness --input out/merged_inputs/input.toml.0.shared --circuit target/poseidon.json --protocol REP3 --config ../../configs/party0.toml --out out/witness/witness.wtns.0.shared  &
	RUST_LOG="error" co-noir generate-witness --input out/merged_inputs/input.toml.1.shared --circuit target/poseidon.json --protocol REP3 --config ../../configs/party1.toml --out out/witness/witness.wtns.1.shared  &
	RUST_LOG="error" co-noir generate-witness --input out/merged_inputs/input.toml.2.shared --circuit target/poseidon.json --protocol REP3 --config ../../configs/party2.toml --out out/witness/witness.wtns.2.shared 

# runs the proof generation on three nodes
run-proof-honk:
	co-noir generate-proof --witness out/witness/witness.wtns.0.shared --crs bn254_g1.dat --protocol REP3 --config ../../configs/party0.toml --out out/proofs/proof.0.dat --public-input out/proofs/public_input.0.json --circuit target/poseidon.json &
	RUST_LOG="error" co-noir generate-proof --witness out/witness/witness.wtns.1.shared --crs bn254_g1.dat --protocol REP3 --config ../../configs/party1.toml --out out/proofs/proof.1.dat --public-input out/proofs/public_input.1.json --circuit target/poseidon.json &
	RUST_LOG="error" co-noir generate-proof --witness out/witness/witness.wtns.2.shared --crs bn254_g1.dat --protocol REP3 --config ../../configs/party2.toml --out out/proofs/proof.2.dat --public-input out/proofs/public_input.2.json --circuit target/poseidon.json
